apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::705916831084:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-11LGVQ1D37HIY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::705916831084:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-27T19:10:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "9683"
  uid: 29e251ba-4d0d-44cc-8fe6-4de175b8f05b
